parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Dashboard Integrator.
    #
    ccdn_forum_forum.component.dashboard.integrator:
        class: %ccdn_forum_forum.component.dashboard.integrator.class%
        tags:
            - { name: ccdn_component_dashboard.integrator }
